# Model Training

### scikit - learn

https://scikit-learn.org/stable/

scikitlearn (sklearn) provides simple and efficient tools for predictive data analysis. It is built on NumPy, SciPy, and matplotlib.

First thing, Import all the libraries

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
pd.set_option('display.max_columns', 50)
# import linear regression model
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
# import module for train test split
from sklearn.model_selection import train_test_split

In [7]:
# next load the data
df = pd.read_csv('../data/real_estate.csv')
df.head()

,price,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,popular,recession,property_age,property_type_Condo
0,295850,2013,234,81,1,1,584,2013,0,0,0,1,0,1
1,216500,2006,169,51,1,1,612,1965,0,0,0,0,41,1
2,279900,2012,216,74,1,1,615,1963,0,0,0,1,49,1
3,379900,2005,265,92,1,1,618,2000,33541,1,0,0,5,0
4,340000,2002,88,30,1,1,634,1992,0,0,0,0,10,1

## Linear Regression Model

In [8]:
# seperate input features in x
x = df.drop('price', axis=1) # axis=1 will drop a column.

# store the target variable in y
y = df['price']

**Train Test Split**
* Training sets are used to fit and tune your models.
* Test sets are put aside as "unseen" data to evaluate your models.
* The `train_test_split()` function splits data into randomized subsets.

## First Train / Test split

In [9]:
# Split the dataset
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, stratify=x.property_type_Condo)

In [10]:
x_train.property_type_Condo.value_counts()

property_type_Condo
0    1208
1     280
Name: count, dtype: int64

In [11]:
x_train.head()

,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,popular,recession,property_age,property_type_Condo
1738,1997,524,159,5,4,3060,1981,12632,1,0,0,16,0
481,2006,193,55,3,2,1408,1967,1542,1,0,0,39,0
199,2007,172,59,2,2,1044,1964,0,0,1,0,43,1
434,2009,376,114,3,2,1260,1948,3598,1,0,0,61,0
1759,2002,582,149,5,4,3967,2002,8276,1,0,0,0,0

## Size of each Vector

In [12]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((1488, 13), (1488,), (372, 13), (372,))

## Random Forest Model

In [13]:
# import decision tree model
from sklearn.ensemble import RandomForestRegressor

In [14]:
# create an instance of the model
rf = RandomForestRegressor(n_estimators=200, criterion='absolute_error')

In [15]:
# train the model
rfmodel = rf.fit(x_train,y_train)

In [16]:
# make prediction on train set
ytrain_pred = rfmodel.predict(x_train)

In [17]:
# make predictions on the x_test values
ytest_pred = rfmodel.predict(x_test)

In [18]:
# evaluate the model
test_mae = mean_absolute_error(ytest_pred, y_test)
test_mae

41972.16925403226

In [19]:
# Individual Decision Trees
# tree.plot_tree(rfmodel.estimators_[2], feature_names=dtmodel.feature_names_in_)

## Pickle:

* The pickle module implements a powerful algorithm for serializing and de-serializing a Python object structure.

* The saving of data is called Serialization, and loading the data is called De-serialization.

**Pickle** model provides the following functions:
* **`pickle.dump`** to serialize an object hierarchy, you simply use `dump()`.
* **`pickle.load`** to deserialize a data stream, you call the `loads()` function.

In [20]:
# import pickle to save model
import pickle

# Save the trained model on the drive
pickle.dump(rfmodel, open('rf_model_real_estate.pkl','wb'))